# Generated by Django 2.2.16 on 2022-09-14 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220914_2222'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_to_following_follow',
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
